sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
language: node_js
node_js:
- '8'
cache:
  yarn: true
branches:
  except:
  - stable
before_install:
- export START_TIME=$( date +%s )
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm i -g yarn
install:
- yarn add @ckeditor/ckeditor5-dev-tests
- ckeditor5-dev-tests-install-dependencies
script:
- ckeditor5-dev-tests-travis
after_success:
- ckeditor5-dev-tests-save-revision
after_script:
- export END_TIME=$( date +%s )
- ckeditor5-dev-tests-notify-travis-status
env:
  global:
  - secure: UPzxX+4UVjCIAR2yKQYhAjXlFNIqqctBIqQkwE/ZG0HxRVrTRSkx0yw0Lq0zEUn2FVNWkZ92PiXgxOd4RmliKgZdE3hqKcZrKa+8LVj+eqKMi1tDLFx+6hIChRYDf9ua20trxl7FoVEbOhlesTmyjhX1aNdhL6gJHIQdgA3koAI9vBaQ0pPi2uGxQXaUTkgT7tLIoMBS+dZXR980HugfNVXuSrT5vXM/c3dpCO3OQkFV6MTdxzDUJihzjsf88Ipj8r/OxO8Lbr+ym4RO/J1uR7hNxn9kk2qnSYwPHL71YAsftNv0nSIlU40fap7MuasFSeGzpxIfJRQtNjpgvKDZNBkOaRuitp82fQSZHYzWr+Q7gsrHdEGfLqjfvrfj0b/us/na+NsT7J1/kYzxyKBl/wCP5h7c+GkJ6ombVrGchbzBoDXiU2iY58nxMwuld4M3mjruGLBa2ZxSQYx+3+14p2jEM7bZUbqey10AH7GDksDAPOt3Bgim0Xst7wmAbnqFbQCCFKcP/0iuRQPw7numhlvGNccQxJn9WrheEay1n8EXA0EJtR+vAImttEJtfc7LwThF2ZgTKjg5AoCkI0bP5LEoYt4p9kJnJmC9iiHuyTH0nfkXc22VLntZdj3nA+31bhIjRxOeWJL2hJtepIkMb4XlDRU05WFt0704j8Z2jHk=
  - secure: SfzG0BCUJZNhcEZqFtJnsN/8KuAR0WzahPSoNjyOxalD+TlVo0K6q+Yi2BjO0/3KLi41b4kl8VuFjdvhoyoDR+bbILOH0GyxzjTNoJGaHZzKODQbPHCFkcpgGetibiLNPt+BtL0JdkUNkE0jolUb05IdVZw92EClIKU/qxB9yhIa7/R9AdlpVB1Zkh3S3Q/4zKtoH3kYnhL80be7RMM/f8WB7lc9/s8Yodk9xV078zaL4CibeG3n/SKINRliGw+JvefmZcoDt9Z1qKXFb9dwzMZZwb+RLpcibvikmeix8cxKG69NF8yqwZYviTMitBGaZcC5vwOrMJDGY5x6t5GVWg7o0UXk2OgO7I/RZBKAXzGo0VnYYJcjfIYl+9mAUvqZSzoRiqwALpvM7KOFEnDWa6PP+hZVRbWdbkgUUpPySxRh7FxeuuV9FXJl3k4Fbi9Ep588nvDbz2T9Y/MR/mOVMO2TSeVLWjs+/c0Zx/Vs30TwWwjWyHcJXJFc6/4bpG+bUKhlENcNo20Qui9lDR8wxETBJNFbtJzSF7FDTQ6Nv8qooEnAeA/nxHFVUyE3ieB5NOAZzeBYVfvo/WNjP32Os2nC9GJkBwAOqR1tdq+/xdOfGyGO9extmvFb60pSbemgdZFJZFI8JM33upUn4sUqXuPtAR8LLV/3XKexcjFVQw4=
  - secure: PYUCapEGtw69Kpp1/cT0FvqkQL3EyiQuZq7qWMH9eBZ1tsNWUk4njCH6p+KAiuTlRzEH3WPeHq+LByjdm+W/m8n4Ch50yMeJR2x1yEwZ3ttV/Fh7KofaaybHneoJAzrT8vOEY4zIA/y+go6jmTMCGFerKr28NCDog6JGdH/e7l9xJffUrr6dWgdgkw8YiPokorptyMPrYjNyMiCGpq/aaEJavOGOmmA+nXBmvr3gPQiVwkOKZPcIfeBBOd0bcx9GiFONWVXg5nC0u+zAVxcOo/tFkKQbzbhzjnurmiVYepkccohP0sZq9H9kSkBRGxsrY4o8ei6z3n4vjsiYyaLwbmCUkGJgNzY8qUz6gSjiaaYaLOrrwNXIrHjt27TNgVM1zQieVQY3Y/j0ti2qhfFZu2tYotu5BW0xIpX4muPh4aS3DT8WZqsckfQ2/BrA1oVi4cP7AStobI2axLNlTJVBmrJQZEy1wiyKJOL0b3C7QpD6v5CVrUmXqo2JvD1uJtosI9jmA7dTeOtSx4xqryKrNB5VazF1eeH2pzoAXTy5BRrEms1+iV628bptbr8jzKBYQe579IC6GV6zV1RpF5Ime2SyXOwrmlDI3jCusQPdc9kLZOrh8SCCsIJ4Xxa+aswdrqtzxaP6xyjX//i63dfQps5uT7HQEBhHL54m1bQNabs=
